name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # Every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: |
          curl -I https://https://moneytracker-pfuy.onrender.com
